// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVc4njGzV9pR67NvcslY6E2tHBzPRL_PM',
    appId: '1:247456441369:web:0b7e6fbddde1248a1bf688',
    messagingSenderId: '247456441369',
    projectId: 'epayment-33bc0',
    authDomain: 'epayment-33bc0.firebaseapp.com',
    storageBucket: 'epayment-33bc0.firebasestorage.app',
    measurementId: 'G-SRNRE2B8Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3P9nN834mulpEo2nKVtYW5SQl8L2gSiU',
    appId: '1:247456441369:android:780fd56d5e4a4d721bf688',
    messagingSenderId: '247456441369',
    projectId: 'epayment-33bc0',
    storageBucket: 'epayment-33bc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FqgL5wFH20XRQCRLV7R1YBn0SbVCZfc',
    appId: '1:247456441369:ios:add24faa289ee7c91bf688',
    messagingSenderId: '247456441369',
    projectId: 'epayment-33bc0',
    storageBucket: 'epayment-33bc0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9FqgL5wFH20XRQCRLV7R1YBn0SbVCZfc',
    appId: '1:247456441369:ios:add24faa289ee7c91bf688',
    messagingSenderId: '247456441369',
    projectId: 'epayment-33bc0',
    storageBucket: 'epayment-33bc0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVc4njGzV9pR67NvcslY6E2tHBzPRL_PM',
    appId: '1:247456441369:web:fb013088c1f243bc1bf688',
    messagingSenderId: '247456441369',
    projectId: 'epayment-33bc0',
    authDomain: 'epayment-33bc0.firebaseapp.com',
    storageBucket: 'epayment-33bc0.firebasestorage.app',
    measurementId: 'G-XYFWF9R4F1',
  );
}
