// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYs9xLklQ35fAWYWFpur8QyM5RKckhvA',
    appId: '1:88461172225:web:d2b943c3377e070ca1ea00',
    messagingSenderId: '88461172225',
    projectId: 'epayment-7d83b',
    authDomain: 'epayment-7d83b.firebaseapp.com',
    storageBucket: 'epayment-7d83b.firebasestorage.app',
    measurementId: 'G-40SJMX2S1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Gt4uwC139e0h8Y-A-5hqdyCMPjZaY7E',
    appId: '1:88461172225:android:26455cd21ce83d26a1ea00',
    messagingSenderId: '88461172225',
    projectId: 'epayment-7d83b',
    storageBucket: 'epayment-7d83b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3PQL6aMdjUqSZbHYWFOyqpYm-1UN7rs',
    appId: '1:88461172225:ios:faf31c9b38690142a1ea00',
    messagingSenderId: '88461172225',
    projectId: 'epayment-7d83b',
    storageBucket: 'epayment-7d83b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3PQL6aMdjUqSZbHYWFOyqpYm-1UN7rs',
    appId: '1:88461172225:ios:faf31c9b38690142a1ea00',
    messagingSenderId: '88461172225',
    projectId: 'epayment-7d83b',
    storageBucket: 'epayment-7d83b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrYs9xLklQ35fAWYWFpur8QyM5RKckhvA',
    appId: '1:88461172225:web:6cb9d443bbd092a6a1ea00',
    messagingSenderId: '88461172225',
    projectId: 'epayment-7d83b',
    authDomain: 'epayment-7d83b.firebaseapp.com',
    storageBucket: 'epayment-7d83b.firebasestorage.app',
    measurementId: 'G-5QQ2KVBSY4',
  );
}
